site_name: "Grupo 8"
site_url: "https://requisitos-de-software.github.io/2024.2-Sympla/"

theme:
  name: material 

nav:
  - Home: index.md
  - Atas:
    - Ata 1º reunião: Atas/ata1.md
  - Planejamento: 
    - Ferramentas: planejamento/ferramentas.md
    - Aplicativos Avaliados: planejamento/aplicativo.md
    - HeatMap: planejamento/heatmap.md
    - Aplicativo Selecionado: planejamento/aplicativo_selecionado.md
  - Apresentações: apresentacoes.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/requisitos-de-software
