site_name: "Grupo 8"
site_url: "https://requisitos-de-software.github.io/2024.2-Sympla/"

theme:
  name: material 

nav:
  - Home: index.md
  - Atas: atas.md
  - Planejamento: 
    - Ferramentas: planejamento/ferramentas.md
    - Aplicativo selecionado: planejamento/aplicativo.md
  - Apresentações: apresentacoes.md
  - Ferramentas: ferramentas.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/requisitos-de-software
