site_name: "Grupo 8"
site_url: "https://requisitos-de-software.github.io/2024.2-Sympla/"

repo_url: "https://github.com/Requisitos-de-Software/2024.2-Sympla/"

theme:
  name: 'material'
  font:
    text: Open Sans
  language: pt-BR
  favicon: assets/sympla-icon.png
  logo: assets/sympla.png
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

  palette:
    - scheme: default  # Modo claro
      primary: 'dark blue'
      accent: 'light blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate  # Modo escuro
      primary: 'blue grey'
      accent: 'cyan'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: high-contrast  # Modo de alto contraste
      primary: 'black'
      accent: 'yellow'
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast

nav:
  - Home: index.md
  - Atas:
    - Ata 1º reunião: Atas/ata1.md
    - Ata 2º reunião: Atas/ata2.md
  - Planejamento:
    - Cronograma de Atividades: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Aplicativos Avaliados: planejamento/aplicativo.md
    - HeatMap: planejamento/heatmap.md
    - Aplicativo Selecionado: planejamento/aplicativo_selecionado.md
  - Pré-rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich_picture.md
  - Elicitação:
    - Perfil do usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Técnicas:
      - Questionário: elicitacao/tecnicas/questionario.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Introspecção: elicitacao/tecnicas/introspeccao.md
    - Requisitos:
      - Requisitos Elicitados: elicitacao/requisitos/requisitos_elicitados.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao1.md
  - Verificação:
    - Geral: verificaçao/verificacao_geral.md
    - Grupo 8:
      - Entrega 1:
        - Planejamento da Verificação: verificaçao/grupo8/entrega1.md
        - Lista de Verificação executada: verificaçao/grupo8/lista_verificacao.md
    - Grupo + 1 - Bluesky:
      - Entrega 1:
        - Planejamento da Verificação - Bluesky: verificaçao/grupo+1/entrega1_grupo1.md
        - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao_grupo1.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2024.2-Sympla
