site_name: "Grupo 8"
site_url: "https://requisitos-de-software.github.io/2024.2-Sympla/"

repo_url: "https://github.com/Requisitos-de-Software/2024.2-Sympla/"

markdown_extensions:
  - admonition
  - pymdownx.details
theme:
  name: 'material'
  font:
    text: Open Sans
  language: pt-BR
  favicon: assets/sympla-icon.png
  logo: assets/sympla.png
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

  palette:
    - scheme: default  # Modo claro
      primary: 'dark blue'
      accent: 'light blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate  # Modo escuro
      primary: 'blue grey'
      accent: 'cyan'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: high-contrast  # Modo de alto contraste
      primary: 'black'
      accent: 'yellow'
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast

nav:
  - Home: index.md
  - Atas:
    - Ata 1º reunião: Atas/ata1.md
    - Ata 2º reunião: Atas/ata2.md
    - Ata 3º reunião: Atas/ata3.md
    - Ata 4º reunião: Atas/ata4.md
    - Ata 5º reunião: Atas/ata5.md
    - Ata 6º reunião: Atas/ata6.md
    - Ata 7º reunião: Atas/ata7.md
    - Ata 8º reunião: Atas/ata8.md
  - Planejamento:
    - Cronograma de Atividades: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Aplicativos Avaliados: planejamento/aplicativo.md
    - HeatMap: planejamento/heatmap.md
    - Aplicativo Selecionado: planejamento/aplicativo_selecionado.md
  - Pré-rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich_picture.md
  - Elicitação:
    - Perfil do usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Técnicas:
      - Questionário: elicitacao/tecnicas/questionario.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Introspecção: elicitacao/tecnicas/introspeccao.md
      - Entrevistas:
        - Manoela: elicitacao/tecnicas/entrevista.md
        - Leonardo: elicitacao/tecnicas/entrevista2.md
    - Requisitos:
      - Requisitos Elicitados: elicitacao/requisitos/requisitos_elicitados.md
    - Priorização:
      - Three Level Scale: elicitacao/priorizacao/three_level_scale.md
      - In or Out: elicitacao/priorizacao/in_or_out.md
  - Modelagem:
      - Cenários: modelagem/cenarios.md
      - Léxicos: modelagem/lexico.md
      - Casos de uso: modelagem/casos_de_uso.md
      - Especificação Suplementar: modelagem/especificacao_suplementar.md
      - Modelagem Ágil:
        - NFR Framework: modelagem/nfr.md
        - Backlog: modelagem/backlog.md
        - Histórias de Usuário: modelagem/historias_usuario.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao1.md
    - Apresentação 2: apresentacoes/apresentacao2.md
    - Apresentação 3: apresentacoes/apresentacao3.md
    - Apresentação 4: apresentacoes/apresentacao4.md
    - Apresentação 5: apresentacoes/apresentacao5.md
    - Apresentação 6: apresentacoes/apresentacao6.md
  - Pós-rastreabilidade:
    - Backward From: pos-rastreabilidade/backward_from.md
    - Forward From: pos-rastreabilidade/forward_from.md
    - Matriz de Rastreabilidade: pos-rastreabilidade/matriz.md
  - Validação:
    - Protótipo de Alta Fidelidade: validacao/prototipo.md
    - Comprovação Informal: validacao/comprovacao_informal.md
  - Verificação:
    - Verificação por Entrega (antigo):
      - Geral: verificaçao/verificacao_geral.md
      - Grupo 8:
        - Entrega 1:
          - Planejamento da Verificação: verificaçao/grupo8/entrega1/entrega1.md
          - Lista de Verificação executada: verificaçao/grupo8/entrega1/lista_verificacao.md
          - Avaliação da Entrega: verificaçao/grupo8/relatorio_melhorias.md 
        - Entrega 2:
          - Planejamento da Verificação 2: verificaçao/grupo8/entrega2/entrega2.md
          - Lista de Verificação executada: verificaçao/grupo8/entrega2/lista_verificacao2.md
          - Avaliação da Entrega 2: verificaçao/grupo8/relatorio_melhorias2.md
        - Entrega 3:
          - Planejamento da Verificação 3: verificaçao/grupo8/entrega3/entrega3.md
          - Lista de Verificação executada: verificaçao/grupo8/entrega3/lista_verificacao3.md
        - Entrega 4:
          - Planejamento da Verificação 4: verificaçao/grupo8/entrega4/entrega4.md
          - Lista de Verificação executada: verificaçao/grupo8/entrega4/lista_verificacao4.md
        - Entrega 6:
          - Planejamento da Verificação 6: verificaçao/grupo8/entrega6/entrega6.md
          - Lista de Verificação executada: verificaçao/grupo8/entrega6/lista_verificacao6.md
      - Grupo + 1 - Bluesky:
        - Entrega 1:
          - Planejamento da Verificação - Bluesky: verificaçao/grupo+1/entrega1_grupo1.md
          - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao_grupo1.md
        
        - Entrega 2:
          - Planejamento da Verificação 2 - Bluesky: verificaçao/grupo+1/entrega2_grupo1.md
          - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao2_grupo1.md
      
        - Entrega 3:
          - Planejamento da Verificação 3 - Bluesky: verificaçao/grupo+1/entrega3_grupo1.md
          - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao3_grupo1.md

        - Entrega 4:
          - Planejamento da Verificação 4 - Bluesky: verificaçao/grupo+1/entrega4_grupo1.md
          - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao4_grupo1.md

        - Entrega 6:
          - Planejamento da Verificação 6 - Bluesky: verificaçao/grupo+1/entrega6_grupo1.md
          - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao6_grupo1.md
    - Verificação por Artefato (novo):
      - Geral: verificaçao/artefatos/verificacao_geral.md
      - Planejamento:
        - Planejamento: verificaçao/artefatos/planejamento/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/planejamento/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/planejamento/inspecaoBluesky.md
      - Pré-Rastreabilidade:
        - Planejamento: verificaçao/artefatos/pre-rastreabilidade/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/pre-rastreabilidade/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/pre-rastreabilidade/inspecaoBluesky.md
      - Perfil de usuário e Personas:
        - Planejamento: verificaçao/artefatos/perfil-e-personas/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/perfil-e-personas/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/perfil-e-personas/inspecaoBluesky.md
      - Técnicas de Elicitação:
        - Planejamento: verificaçao/artefatos/elicitacao/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/elicitacao/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/elicitacao/inspecaoBluesky.md
      - Técnicas de Priorização:
        - Planejamento: verificaçao/artefatos/priorizacao/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/priorizacao/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/priorizacao/inspecaoBluesky.md
      - Modelagem:
        - Planejamento: verificaçao/artefatos/modelagem/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/modelagem/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/modelagem/inspecaoBluesky.md
      - Ágil:
        - Planejamento: verificaçao/artefatos/agil/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/agil/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/agil/inspecaoBluesky.md
      - Pós-Rastreabilidade:
        - Planejamento: verificaçao/artefatos/pos-rastreabilidade/planejamento.md
        - Autoinspeção Grupo 8 - Sympla: verificaçao/artefatos/pos-rastreabilidade/autoinspecao.md
        - Inspeção Grupo +1 - Bluesky: verificaçao/artefatos/pos-rastreabilidade/inspecaoBluesky.md

  - Entrega Final:
    - Aplicativo escolhido: entrega_final/aplicativo_escolhido.md
    - Planejamento dos recursos e entregas: entrega_final/planejamento.md
    - Execução do projeto: entrega_final/execucao.md
    - Resultados alcançados: entrega_final/resultados.md
    - Ferramentas utilizadas: entrega_final/ferramentas.md
    - Técnicas utilizadas: entrega_final/tecnicas.md
    - Verificação e validação: entrega_final/verificacao_validacao.md
    - Apresentações: entrega_final/apresentacoes.md
    - Facilidades e dificuldades: entrega_final/facilidades_dificuldades.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2024.2-Sympla
