site_name: "Grupo 8"
site_url: "https://requisitos-de-software.github.io/2024.2-Sympla/"

repo_url: "https://github.com/Requisitos-de-Software/2024.2-Sympla/"

theme:
  name: 'material'
  font:
    text: Open Sans
  language: pt-BR
  favicon: assets/sympla-icon.png
  logo: assets/sympla.png
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

  palette:
    - scheme: default  # Modo claro
      primary: 'dark blue'
      accent: 'light blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate  # Modo escuro
      primary: 'blue grey'
      accent: 'cyan'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: high-contrast  # Modo de alto contraste
      primary: 'black'
      accent: 'yellow'
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast

nav:
  - Home: index.md
  - Atas:
    - Ata 1º reunião: Atas/ata1.md
    - Ata 2º reunião: Atas/ata2.md
    - Ata 3º reunião: Atas/ata3.md
    - Ata 4º reunião: Atas/ata4.md
    - Ata 5º reunião: Atas/ata5.md
    - Ata 6º reunião: Atas/ata6.md
  - Planejamento:
    - Cronograma de Atividades: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Aplicativos Avaliados: planejamento/aplicativo.md
    - HeatMap: planejamento/heatmap.md
    - Aplicativo Selecionado: planejamento/aplicativo_selecionado.md
  - Pré-rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich_picture.md
  - Elicitação:
    - Perfil do usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Técnicas:
      - Questionário: elicitacao/tecnicas/questionario.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Introspecção: elicitacao/tecnicas/introspeccao.md
      - Entrevistas:
        - Manoela: elicitacao/tecnicas/entrevista.md
        - Leonardo: elicitacao/tecnicas/entrevista2.md
    - Requisitos:
      - Requisitos Elicitados: elicitacao/requisitos/requisitos_elicitados.md
    - Priorização:
      - Three Level Scale: elicitacao/priorizacao/three_level_scale.md
      - In or Out: elicitacao/priorizacao/in_or_out.md
  - Modelagem:
      - Especificação Suplementar: modelagem/especificacao_suplementar.md
      - Léxicos: modelagem/lexico.md
      - Cenários: modelagem/cenarios.md
      - Casos de uso: modelagem/casos_de_uso.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao1.md
    - Apresentação 2: apresentacoes/apresentacao2.md
    - Apresentação 3: apresentacoes/apresentacao3.md
  - Verificação:
    - Geral: verificaçao/verificacao_geral.md
    - Grupo 8:
      - Entrega 1:
        - Planejamento da Verificação: verificaçao/grupo8/entrega1/entrega1.md
        - Lista de Verificação executada: verificaçao/grupo8/entrega1/lista_verificacao.md
        - Avaliação da Entrega: verificaçao/grupo8/relatorio_melhorias.md 
      - Entrega 2:
        - Planejamento da Verificação 2: verificaçao/grupo8/entrega2/entrega2.md
        - Lista de Verificação executada: verificaçao/grupo8/entrega2/lista_verificacao2.md
        - Avaliação da Entrega 2: verificaçao/grupo8/relatorio_melhorias2.md
      - Entrega 3:
        - Planejamento da Verificação 3: verificaçao/grupo8/entrega3/entrega3.md
        - Lista de Verificação executada: verificaçao/grupo8/entrega3/lista_verificacao3.md
    - Grupo + 1 - Bluesky:
      - Entrega 1:
        - Planejamento da Verificação - Bluesky: verificaçao/grupo+1/entrega1_grupo1.md
        - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao_grupo1.md
        
      - Entrega 2:
        - Planejamento da Verificação 2 - Bluesky: verificaçao/grupo+1/entrega2_grupo1.md
        - Lista de Verificação executada - Bluesky: verificaçao/grupo+1/lista_verificacao2_grupo1.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2024.2-Sympla
